# Generated by Django 3.1 on 2021-07-18 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_item', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Long Sleeve Shirt', 'Long Sleeve Shirt'), ('Short Sleeve Shirt', 'Short Sleeve Shirt')], default='T-Shirt', max_length=25)),
                ('customized_order_number', models.CharField(max_length=20)),
                ('front_text', models.CharField(blank=True, max_length=255)),
                ('back_text', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(upload_to='customized_orders/')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('design_image', models.ImageField(upload_to='customized_orders')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
