# Generated by Django 3.1 on 2021-07-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedorder',
            name='design_image',
            field=models.ImageField(upload_to='customized_orders/'),
        ),
        migrations.AlterField(
            model_name='customizedorder',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Accepted', max_length=10),
        ),
    ]
