# Generated by Django 3.1 on 2021-07-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0002_auto_20210719_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedorder',
            name='customized_order_number',
        ),
        migrations.RemoveField(
            model_name='customizedorder',
            name='ip',
        ),
    ]
