# Generated by Django 3.1 on 2021-07-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0003_auto_20210719_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedorder',
            name='design_image',
        ),
        migrations.RemoveField(
            model_name='customizedorder',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='customizedorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customizedorder',
            name='type_of_item',
        ),
    ]
