# Generated by Django 3.1 on 2021-07-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0005_customizedorder_type_of_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedorder',
            name='type_of_item',
        ),
    ]
