# Generated by Django 3.1 on 2021-07-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0007_customizedorder_design_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedorder',
            name='design_image',
        ),
    ]
