# Generated by Django 3.1 on 2021-07-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0008_remove_customizedorder_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedorder',
            name='design_image',
            field=models.ImageField(blank=True, upload_to='customized_orders/'),
        ),
        migrations.AddField(
            model_name='customizedorder',
            name='logo',
            field=models.ImageField(blank=True, upload_to='customized_orders/'),
        ),
    ]
