# Generated by Django 3.1 on 2021-07-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0011_remove_customizedorder_type_of_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedorder',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Accepted', max_length=10),
        ),
    ]
