# Generated by Django 3.1 on 2021-07-19 06:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0012_customizedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedorder',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
