# Generated by Django 3.1 on 2021-07-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0013_auto_20210719_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedorder',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
