# Generated by Django 3.1 on 2021-07-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0014_auto_20210719_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedorder',
            name='order_type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
