# Generated by Django 3.1 on 2021-07-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0015_customizedorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedorder',
            name='customized_order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
