# Generated by Django 3.1 on 2021-07-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0016_customizedorder_customized_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
