# Generated by Django 3.1 on 2021-06-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('colour', 'color'), ('size', 'size')], max_length=100),
        ),
    ]
