# Generated by Django 3.1 on 2021-06-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210606_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('colour', 'colour'), ('size', 'size')], max_length=100),
        ),
    ]
