# Generated by Django 3.1 on 2021-07-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
