# Generated by Django 3.1 on 2021-07-26 08:39

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(blank=True, max_length=150)),
                ('front_text', models.CharField(blank=True, max_length=255)),
                ('back_text', models.CharField(blank=True, max_length=255)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('quantity', models.IntegerField()),
                ('design_image', models.ImageField(blank=True, upload_to='supplier_customized_orders/')),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
        ),
    ]
