# Generated by Django 3.1 on 2021-07-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierorder',
            old_name='user',
            new_name='supplier',
        ),
    ]
